version: "3.9"
services:
  todo-app:
    build: docker/images/getting-started/app
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    volumes:
      - todo-codebase:/app
    networks:
      todo-app:
    depends_on:
      - todo-db

  todo-db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    volumes:
      - todo-mysql-data:/var/lib/mysql
    networks:
      todo-app:
        aliases:
          - mysql

volumes:
  todo-codebase:
    driver_opts:
      type: none
      device: "$PWD"/docker/images/getting-started/app
      o: bind
  todo-mysql-data:

networks:
  todo-app:
