# Bump this via helm in a github pipeline instead
image: ghcr.io/reload/harvester:latest

ingress:
  host: harvester.reload.dk
  # enable prod and disable staging to issue REAL certs
  #issuer: letsencrypt-prod
  issuer: letsencrypt-prod

harvester:
  pv:
    size: 100Mi
