---
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.labels.db }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.services.db.name }}
spec:
  ports:
  - port: {{ .Values.services.db.port }}
    protocol: TCP
    targetPort: {{ .Values.services.db.targetPort }}
  {{- with .Values.labels.db }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
