name: Provision, check & deprovision docker containers

on: [push, pull_request]

jobs:

  containers:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Spawn docker containers and remove them on success
      run: |
        ./create_containers.sh
        ./gc.sh
      shell: bash
