name: Tests

on:
  pull_request:

jobs:

  shellcheck-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Install shellcheck
      run: sudo apt install shellcheck

    - uses: actions/checkout@v2

    - name: Check our scripts for errors
      run: shellcheck ./*.sh
