name: Tests

on:
  pull_request:

jobs:

  shellcheck-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Install shellcheck
      run: sudo apt install shellcheck

    - name: Check our script for errors
      uses: actions/checkout@v2
      run: shellcheck ./containers.sh
